[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["test_gql"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "test_gql"
  org = "yashodperera"
  version = "1.0.1"

